server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    username: root
    password: lm12138
    url: jdbc:mysql://localhost:3306/dianping?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: lm12138
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
  jackson:
    default-property-inclusion: non_null # JSON?????????

mybatis-plus:
  type-aliases-package: com.lm.dianping.entity # ?????
logging:
  level:
    com.lm: debug
  pattern:
    dateformat: mm:ss.SSS
